apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 062255690930.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newName: 062255690930.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newTag: e052d300
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
